from pathlib import Path

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt
from pptx import Presentation
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from pptx.enum.shapes import MSO_SHAPE
from pptx.dml.color import RGBColor
from pptx.util import Inches as PI, Pt as PPt

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'reports'/'outline-defense-2026-10-10'
TEMPLATE=OUT/'source-templates'/'2026-USeP-Powerpoint-Presentation-Template.pptx'
TITLE='EVALUATION OF LAND AND WATER RESOURCE MANAGEMENT FOR PANTARON RANGE, MINDANAO'

def fmt(run,size=12,bold=False):
    run.font.name='Arial'; run.font.size=Pt(size); run.bold=bold

def heading(doc,text,level=1):
    p=doc.add_paragraph(); p.alignment=WD_ALIGN_PARAGRAPH.CENTER if level==1 else WD_ALIGN_PARAGRAPH.LEFT
    p.paragraph_format.space_before=Pt(12); p.paragraph_format.space_after=Pt(6)
    fmt(p.add_run(text.upper() if level==1 else text),12,True)

def para(doc,text,indent=True):
    p=doc.add_paragraph(); p.alignment=WD_ALIGN_PARAGRAPH.JUSTIFY; p.paragraph_format.line_spacing=2; p.paragraph_format.space_after=Pt(0)
    if indent:p.paragraph_format.first_line_indent=Inches(.5)
    fmt(p.add_run(text)); return p

def bullets(doc,items):
    for item in items:
        p=doc.add_paragraph(); p.paragraph_format.left_indent=Inches(.5); p.paragraph_format.first_line_indent=Inches(-.25); p.paragraph_format.line_spacing=1.5
        fmt(p.add_run('• '),12,True); fmt(p.add_run(item))

def make_docx():
    d=Document(); s=d.sections[0]; s.page_width=Inches(8.5); s.page_height=Inches(11); s.left_margin=Inches(1.5); s.right_margin=Inches(1); s.top_margin=s.bottom_margin=Inches(1)
    p=d.add_paragraph(); p.alignment=WD_ALIGN_PARAGRAPH.CENTER; p.paragraph_format.space_before=Inches(.6); fmt(p.add_run(TITLE),14,True)
    for _ in range(4): d.add_paragraph()
    for x in ['JOSHUA S. DE LEON','MASTER OF SCIENCE IN ENGINEERING','Land and Water Resources Engineering and Technology','Graduate School of Engineering','University of Southeastern Philippines','OCTOBER 2026']:
        p=d.add_paragraph();p.alignment=WD_ALIGN_PARAGRAPH.CENTER;fmt(p.add_run(x),12,True)
    d.add_page_break(); heading(d,'CHAPTER 1 – INTRODUCTION')
    heading(d,'Background of the Study',2)
    para(d,'The Pantaron Range is discussed in planning, conservation, Indigenous-governance, and river-basin sources as an important upland landscape in Mindanao. Yet the available materials reviewed for this proposal do not provide one spatially consistent evaluation that links land-resource condition, water-resource condition, documented pressures, and management responses across a clearly defined set of Pantaron-related catchments. Reported logging, forest conversion, mining interest, erosion, drought, water shortage, and watershed concerns vary in date and geographic scope and cannot be treated as measured range-wide conditions.')
    para(d,'Land and water are connected through catchments. Vegetation cover, cultivation, exposed soil, terrain, and riparian condition influence runoff and erosion susceptibility, while drainage networks connect upstream land conditions with downstream water bodies. Rainfall controls water inputs but does not by itself measure dependable supply. Satellite observations and GIS can establish comparable spatial indicators, but field measurements and institutional records are required for claims concerning water quality, stream condition, land management practice, or management effectiveness.')
    para(d,'This study will therefore evaluate selected Pantaron-linked catchments through three evidence layers: resource condition, pressures and risks, and management response. Remote sensing will be used to measure land cover, forest configuration, terrain, riparian cover, rainfall, drainage, and observable surface water. Targeted field validation will address uncertain land-cover classes, erosion indicators, stream condition, and selected water measurements. Official plans and project records will document management actions. Causal or effectiveness claims will be made only when intervention timing, location, implementation, outcomes, and a defensible comparison are available.')
    heading(d,'Statement of the Problem',2)
    para(d,'Land and water resource management decisions for Pantaron require a defensible description of where resource conditions and pressures occur, which catchments connect them, what management actions are documented, and where important information remains missing. Existing reports and datasets have different boundaries, dates, resolutions, and evidentiary strength. Without a common catchment framework and explicit validation, broad claims about degradation, water availability, or management success may be misleading.')
    bullets(d,['What are the defensible boundaries and physical characteristics of the selected Pantaron-linked management catchments?','What land-cover, forest-configuration, terrain, riparian, and erosion-susceptibility conditions occur within the selected catchments?','What rainfall, drainage, surface-water, and field-observed water conditions can be established at defensible spatial and temporal scales?','Which protection, restoration, sustainable-land-management, monitoring, and water-management actions are documented, and what is their spatial and temporal coverage?','Which areas require protection, restoration, improved land management, monitoring, or additional hydrologic investigation, considering uncertainty?'])
    heading(d,'Objectives of the Study',2)
    para(d,'The general objective will be to evaluate land and water resource management in selected catchments associated with the Pantaron Range using remote sensing, GIS, secondary records, and targeted field validation.')
    bullets(d,['Delineate and characterize selected management catchments and their relationship to a verified Pantaron reference boundary.','Evaluate land-resource condition using land cover and, if feasible, comparable change, forest configuration, terrain constraints, riparian condition, and erosion susceptibility.','Evaluate water-resource condition using rainfall variability, drainage characteristics, surface-water occurrence, and targeted field measurements where feasible.','Inventory and spatially relate documented management interventions and governance arrangements to measured land and water indicators.','Classify management needs using transparent decision rules and evaluate sensitivity and uncertainty.'])
    heading(d,'Significance of the Study',2)
    para(d,'The study will provide a repeatable evidence base for agencies, local governments, researchers, and authorized community partners to identify where protection, restoration, agricultural conservation, riparian management, monitoring, or further hydrologic assessment may be needed. It will also identify where remote evidence is inadequate and field or institutional information is necessary. The work will not claim institutional or community endorsement without documented participation.')
    heading(d,'Scope and Limitation of the Study',2)
    para(d,'The study will cover two to four selected complete catchments whose outlets and relationship to the Pantaron reference boundary can be documented. Core analyses will include land cover, forest configuration, terrain, riparian cover, erosion susceptibility, drainage, rainfall, and management-response inventory. Land-cover change will be retained only if two comparable periods and independent validation are feasible. RUSLE will be used only if defensible rainfall erosivity, soil erodibility, topographic, cover-management, and support-practice inputs are available; otherwise the output will be labeled erosion susceptibility rather than soil-loss rate.')
    para(d,'Targeted field work will not represent the entire range unless a probability-based sample is implemented. A single water-sampling visit will be treated as a snapshot, not long-term water quality, dependable flow, or regulatory compliance. Satellite cover does not establish tenure, land-use intention, management practice, soil fertility, or community preference. Management effectiveness cannot be inferred from spatial overlap or correlation alone.')
    heading(d,'Definition of Terms',2)
    for x in ['Management catchment – a complete upstream hydrologic unit used to connect land condition, water condition, pressures, and management actions.','Land-resource condition – remotely or directly observed cover, forest configuration, terrain, riparian condition, and defensibly modeled susceptibility.','Water-resource condition – rainfall, drainage, surface-water occurrence, and measured field conditions; it is not synonymous with usable water supply.','Management response – a documented protection, restoration, conservation, monitoring, allocation, or governance action with identifiable authority, place, and period.','Management need – a transparent screening class indicating protection, restoration, sustainable land management, monitoring, or further investigation.']: para(d,x,False)

    d.add_page_break(); heading(d,'CHAPTER 2 – REVIEW OF LITERATURE AND THEORETICAL FRAMEWORK')
    heading(d,'Related Literature and Studies',2)
    for h,t in [
      ('Pantaron land, water, and governance context','Reviewed sources describe Pantaron-related forest, watershed, Indigenous-governance, protected-area, drought, and downstream river-basin concerns. These sources establish management questions but differ in date, scope, and evidence. Richelle et al. (2018) demonstrates locally varied soil knowledge in Bendum and cautions against range-wide generalization.'),
      ('Remote assessment of land resources','Sentinel-2 supports land-cover and vegetation mapping when clouds, shadows, seasonality, reference labels, and terrain illumination are addressed. Forest fragmentation and riparian metrics add management meaning only when class accuracy and analysis scale are defensible. Auxtero and Villamor (2026) provide a USeP-affiliated Philippine image-classification example, but their classes and performance are not transferable to Pantaron.'),
      ('Terrain and erosion susceptibility','A DEM can support catchment, slope, flow, and drainage analysis, but results depend on surface artifacts, conditioning, outlet location, and stream threshold. Soil-loss models require more than slope and cover. RUSLE should be used only when every factor is supported and uncertainty is evaluated.'),
      ('Water-resource assessment','CHIRPS v3 can characterize rainfall amount, seasonality, and anomalies at coarse native support. Drainage geometry and rainfall are indicators, not measurements of dependable supply. Surface-water occurrence, field discharge, or water-quality measurements require appropriate temporal design and quality control.'),
      ('Management and decision support','GIS overlays can organize evidence for management, as illustrated by Cogay et al. (2020) for an irrigation-specific decision. Pantaron management classes must use locally justified rules rather than imported weights. Intervention effectiveness requires evidence of implementation, timing, outcome, and comparison.'),
    ]: heading(d,h,2); para(d,t)
    heading(d,'Theory Base',2); para(d,'The study will use the Driver–Pressure–State–Impact–Response logic as an organizing framework, not as proof of causation. Reported drivers and pressures will be linked to measured resource-state indicators; management responses will be documented separately. Catchment systems thinking will connect upstream land conditions to downstream water pathways while preserving alternative explanations and uncertainty.')
    heading(d,'Conceptual Framework',2); para(d,'Verified boundary and management catchments → data and evidence audit → land condition + water condition + pressures → independent validation and uncertainty → management-response inventory → transparent management-need classification → protection, restoration, sustainable-management, monitoring, and research recommendations.',False)
    heading(d,'Research Assumptions',2); bullets(d,['Selected datasets will contain sufficient valid observations for the final periods.','Authoritative or traceable boundary, hydrography, and management records can be obtained.','Field access, permissions, safety, and equipment will determine the extent of validation.','Observed association between management actions and resource condition will not be interpreted as causation without an adequate evaluation design.'])

    d.add_page_break(); heading(d,'CHAPTER 3 – METHODOLOGY')
    heading(d,'Method Used',2); para(d,'The study will use a mixed geospatial evaluation design combining remote sensing, GIS, field validation, document review, and descriptive comparison among selected catchments. Quantitative indicators will measure resource condition; documentary evidence will identify management responses; field evidence will validate selected observations. Interviews, if needed, will proceed only after adviser/program approval and research-ethics clearance.')
    heading(d,'Sources of Data',2); bullets(d,['Sentinel-2 Level-2A imagery for land cover, vegetation, riparian cover, and comparable change where feasible.','Copernicus DEM GLO-30 for terrain, catchments, and drainage, with surface-model limitations disclosed.','CHIRPS v3 for rainfall totals, seasonality, anomalies, and dry-spell indicators at native 0.05-degree support.','Authoritative boundary, hydrography, protected-area, ancestral-domain, planning, and project records where accessible and legally usable.','Independent dated imagery, field land-cover observations, stream observations, gauges, and calibrated water-quality measurements where feasible.'])
    heading(d,'Data Gathering Instruments',2); bullets(d,['GIS/remote-sensing processing log recording product, version, period, resolution, CRS, cloud handling, parameters, and retrieval date.','Land-validation form recording coordinates, date/time, dominant cover, photographs, confidence, and access limitations.','Stream form recording site geometry, weather, recent rainfall, width, depth, velocity/discharge method, riparian condition, and observable disturbance.','Calibrated multiparameter or individual instruments for temperature, pH, electrical conductivity, dissolved oxygen, and turbidity only when equipment and QA/QC are available.','Management-response extraction form recording intervention, authority, location, period, intended outcome, implementation evidence, and monitoring indicator.'])
    heading(d,'Sampling Technique',2); para(d,'Two to four catchments will be purposively selected using documented Pantaron relationship, management relevance, data completeness, contrasting land/water conditions, and feasible validation. Land-cover accuracy samples will use an independent stratified probability design across mapped classes, with spatial separation from training data. Field sites will be allocated toward classification uncertainty, riparian condition, erosion indicators, and accessible stream reaches; limitations from access and safety will be disclosed. Water sites and timing will be selected to answer a defined question and will not be presented as range-wide or year-round evidence.')
    heading(d,'Procedure of the Study',2)
    steps=['Verify boundary sources, outlets, and complete upstream catchments; compute catchment overlap with the Pantaron reference.','Audit datasets and harmonize only where scientifically justified; preserve native spatial support in interpretation.','Prepare Sentinel-2 composites; map a modest class scheme; compare a random-forest classifier with an interpretable baseline; map no-data areas explicitly.','Validate land cover independently; report confusion matrix, user’s and producer’s accuracy, and area-adjusted estimates with confidence intervals where the design permits.','Calculate forest-patch, edge/core, riparian-cover, slope, and terrain indicators at sensitivity-tested scales. Add RUSLE only if all factors and evaluation evidence are defensible.','Condition the DEM, derive flow direction/accumulation, delineate drainage, test extraction thresholds, and compare with reference hydrography.','Summarize complete CHIRPS v3 records by catchment and calculate rainfall seasonality, anomalies, and dry-spell indicators without downscaling claims.','Conduct approved field validation; calibrate instruments, document QA/QC, and label water observations as snapshots unless repeated sampling supports temporal inference.','Inventory management responses from official and traceable records; map coverage where spatial evidence exists; distinguish planned, implemented, monitored, and evaluated actions.','Classify management needs through explicit rules and sensitivity tests; report evidence strength and uncertainty for each catchment and recommendation.']
    for i,x in enumerate(steps,1): para(d,f'{i}. {x}',False)
    heading(d,'Statistical Treatment',2); para(d,'Descriptive statistics will summarize land-cover proportions, landscape metrics, terrain, rainfall, drainage, surface-water, and field observations by catchment. Classification evaluation will use confusion-matrix measures and confidence intervals. Rainfall comparison may use bias, mean absolute error, or correlation only when appropriate independent gauge records exist. Differences among catchments will not be tested by treating adjacent pixels as independent observations. Any management classification will be accompanied by threshold sensitivity and an evidence-strength rating. Causal effectiveness tests will be excluded unless a defensible before–after or comparison design and adequate observations become available.')
    heading(d,'Ethical, Safety, and Data-Governance Considerations',2); para(d,'Field access will require permission, safety planning, and respect for Indigenous and community protocols. Coordinates or knowledge judged sensitive will not be publicly disclosed without authorization. Interviews or identifiable human-participant data will not be collected before ethics clearance. Public maps will distinguish observational evidence from community or institutional claims.')
    heading(d,'REFERENCES')
    for r in ['AUXTERO, A. M. B., and M. M. VILLAMOR. (2026). Deep Learning-Based Methods for Mapping Mangrove Forests in Bohol, Philippines Using Sentinel-2 Imagery. ISPRS Annals X-5/W4-2025:83–89. https://doi.org/10.5194/isprs-annals-X-5-W4-2025-83-2026.','CLIMATE HAZARDS CENTER. (n.d.). CHIRPS v3 documentation and diagnostics. University of California, Santa Barbara.','COGAY, S., I. P. AMPLAYO, R. R. BAYRON, and R. V. CANTONES. (2020). GIS-Based Land Suitability Analysis for Solar Powered Irrigation System in Non-Irrigated Rice Production Areas of Davao Del Norte. SPJRD 25(1):47–73. https://doi.org/10.53899/spjrd.v25i1.45.','COPERNICUS DATA SPACE ECOSYSTEM. (n.d.). Sentinel-2 and Copernicus DEM product documentation.','RICHELLE, L. et al. (2018). Looking for a dialogue between farmers and scientific soil knowledge. Agroecology and Sustainable Food Systems 42(1):2–27. https://doi.org/10.1080/21683565.2017.1322661.']: para(d,r,False)
    path=OUT/'Pantaron_Land_Water_Management_Proposal_Chapters_1_to_3.docx';d.save(path);return path

def clear_slides(prs):
    ids=prs.slides._sldIdLst
    for sld in list(ids): ids.remove(sld)

def textbox(slide,x,y,w,h,text,size=20,bold=False,color=(35,35,35),align=PP_ALIGN.LEFT):
    sh=slide.shapes.add_textbox(PI(x),PI(y),PI(w),PI(h));tf=sh.text_frame;tf.clear();tf.word_wrap=True;tf.vertical_anchor=MSO_ANCHOR.MIDDLE
    p=tf.paragraphs[0];p.alignment=align;r=p.add_run();r.text=text;r.font.name='Arial';r.font.size=PPt(size);r.font.bold=bold;r.font.color.rgb=RGBColor(*color);return sh

def make_pptx():
    prs=Presentation(TEMPLATE); original_slide_count=len(prs.slides); RED=(150,20,25); DARK=(40,40,40); PALE=(247,244,242)
    def content(title,items,section=None):
        s=prs.slides.add_slide(prs.slide_layouts[5]); textbox(s,.65,.28,12,.55,title,25,True,RED)
        if section:textbox(s,10.2,.31,2.35,.3,section,10,True,(110,110,110),PP_ALIGN.RIGHT)
        y=1.12
        for i,item in enumerate(items):
            box=s.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE,PI(.75),PI(y),PI(11.85),PI(.68));box.fill.solid();box.fill.fore_color.rgb=RGBColor(*(PALE if i%2==0 else (255,255,255)));box.line.color.rgb=RGBColor(222,210,205)
            textbox(s,.98,y+.05,11.35,.56,item,15,False,DARK);y+=.78
        return s
    s=prs.slides.add_slide(prs.slide_layouts[2]); textbox(s,1.0,3.65,11.3,1.15,TITLE.title(),24,True,(255,255,255),PP_ALIGN.CENTER);textbox(s,2.2,5.0,8.9,.8,'JOSHUA S. DE LEON\nMSE–Land and Water Resources Engineering and Technology',16,False,(255,255,255),PP_ALIGN.CENTER)
    content('OUTLINE',['The management problem and research gap','Objectives and significance','Land-resource assessment','Water-resource assessment','Management-response evaluation','Validation, integration, and expected outputs'],'OUTLINE')
    content('THE MANAGEMENT PROBLEM',['Pantaron evidence is dispersed across forest, land, watershed, governance, and downstream basin sources.','Reported pressures differ in date and geographic scope; they are not measured range-wide conditions.','Remote sensing can evaluate resource condition—but not management practice or effectiveness by itself.','A common catchment framework is needed to connect upstream land condition, water pathways, and management action.'],'CHAPTER 1')
    content('RESEARCH QUESTION',['What land and water resource conditions occur in selected Pantaron-linked catchments?','Which pressures and risks are supported by spatial or field evidence?','What management responses are documented, where, and with what implementation evidence?','Which areas need protection, restoration, sustainable land management, monitoring, or further hydrologic investigation?'],'CHAPTER 1')
    content('OBJECTIVES',['1  Delineate selected management catchments and relate them to a verified Pantaron boundary.','2  Evaluate land cover/forest condition, terrain, riparian cover, and erosion susceptibility.','3  Evaluate rainfall, drainage, surface-water occurrence, and targeted field water conditions.','4  Inventory and map documented management responses and governance arrangements.','5  Classify management needs using transparent rules, evidence strength, and uncertainty.'],'CHAPTER 1')
    content('CONCEPTUAL FRAMEWORK',['DRIVERS/PRESSURES  •  reported and verified land/water pressures','STATE  •  land cover, forest configuration, terrain, riparian condition, rainfall, drainage, surface water','RESPONSE  •  protection, restoration, conservation, monitoring, water management, governance','EVALUATION  •  independent validation, sensitivity, evidence strength, and management-need classification'],'CHAPTER 2')
    content('LAND-RESOURCE ASSESSMENT',['Sentinel-2 L2A seasonal composites with cloud, shadow, invalid-pixel, and terrain-effect checks.','Validated land-cover classes; comparable change only when both periods have adequate reference evidence.','Forest patch, edge/core, and riparian-cover metrics at defensible analysis scales.','Slope and terrain constraints; erosion susceptibility as the core output.','RUSLE only if R, K, LS, C, P inputs and validation are defensible—otherwise no soil-loss-rate claim.'],'CHAPTER 3')
    content('WATER-RESOURCE ASSESSMENT',['Conditioned DEM, verified outlets, complete catchments, and threshold-tested drainage.','CHIRPS v3 rainfall totals, seasonality, anomalies, and dry spells at native 0.05° support.','Surface-water occurrence only where observation density and mixed pixels permit.','Targeted field measurements: stream geometry/flow and calibrated temperature, pH, EC, DO, turbidity where feasible.','Single visits are snapshots—not dependable supply, long-term quality, or regulatory compliance.'],'CHAPTER 3')
    content('MANAGEMENT-RESPONSE EVALUATION',['Review plans, legal instruments, agency projects, restoration records, monitoring reports, and authorized local evidence.','Record responsible institution, location, period, intended outcome, implementation evidence, and monitoring indicator.','Distinguish planned, implemented, monitored, and evaluated actions.','Claim effectiveness only with intervention exposure, timing, outcome evidence, and a defensible comparison.','Interviews require adviser approval, ethics clearance, permission, and protection of sensitive knowledge.'],'CHAPTER 3')
    content('SAMPLING AND VALIDATION',['Select 2–4 catchments by Pantaron relationship, management relevance, contrast, data completeness, and access.','Use independent stratified probability samples for land-cover accuracy; separate training, tuning, and evaluation.','Target field sites toward uncertain classes, riparian condition, erosion indicators, and accessible streams.','Record coordinates, time, photos, observer confidence, calibration, recent weather, and access limitations.','Report confusion matrix, class accuracy, area uncertainty, and parameter sensitivity.'],'CHAPTER 3')
    content('INTEGRATION FOR MANAGEMENT',['Compare catchments using land condition, water condition, pressure, and response evidence.','Apply explicit decision rules—never an unexplained weighted suitability score.','Assign needs: PROTECT • RESTORE • SUSTAINABLE LAND MANAGEMENT • MONITOR • INVESTIGATE.','Test alternative buffers, thresholds, class errors, outlet positions, and rainfall support.','Attach evidence strength and limitations to every mapped recommendation.'],'CHAPTER 3')
    content('EXPECTED OUTPUTS',['Verified Pantaron-reference and management-catchment map.','Land-cover/forest, terrain, riparian, and erosion-susceptibility outputs.','Rainfall, drainage, surface-water, and field-observation summaries.','Management-intervention inventory and spatial coverage map.','Catchment management-needs matrix with uncertainty and responsible planning use.'],'OUTPUTS')
    content('CRITICAL ITEMS TO COMPLETE',['Authoritative Pantaron boundary, outlets, and selected catchments.','Comparable imagery periods, class scheme, and validation sample-size calculation.','Hydrography, rainfall gauges, field access, instruments, permissions, and safety plan.','Official management plans/intervention records and research-ethics determination.','Primary references for accuracy-adjusted area, landscape metrics, erosion susceptibility, field water QA/QC, and evaluation design.'],'GAPS')
    s=prs.slides.add_slide(prs.slide_layouts[2]);textbox(s,1.25,4.0,10.8,.7,'THE CONTRIBUTION',27,True,(255,255,255),PP_ALIGN.CENTER);textbox(s,1.55,4.85,10.2,1.15,'A defensible evaluation connecting land condition, water condition, management response, and uncertainty within selected Pantaron-linked catchments.',19,False,(255,255,255),PP_ALIGN.CENTER)
    ids=prs.slides._sldIdLst
    for sld in list(ids)[:original_slide_count]: ids.remove(sld)
    path=OUT/'Pantaron_Outline_Defense_USeP_Template.pptx';prs.save(path);return path

if __name__=='__main__':
    print(make_docx());print(make_pptx())
